version: '3'
volumes:
    unsync:
services:
    api:
        build: .
        volumes:
            - ./:/go/src/github.com/naoki-kishi/graphql-redis-realtime-chat
            - unsync:/go/src/github.com/naoki-kishi/graphql-redis-realtime-chat/frontend
        ports:
            - '8080:8080'
        depends_on:
            - redis

        command: fresh

        environment:
            REDIS_URL: 'redis:6379'
            PORT: '8080'
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
