version: '3'
services:
    api:
        build: .
        volumes:
            - ./:/go/src/github.com/naoki-kishi/graphql-redis-realtime-chat
        ports:
            - '8080:8080'
        depends_on:
            - redis

        command: fresh
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
